### ISSUE TITLE
Egészen kaki

### ISSUE THREAD

**Issue by Szaki-dev** [NovySoft/novyNaplo#16]
**Írd le a hibát*
Egy egyszerű, de részletes leírása a hibának

**Hogyan reprodukáljuk**
A hiba reprodukálásához való lépések:
1. Menjünk '...'
2. Nyomjunk '....'
3. Tekerjünk le '....'
4. Meglátjuk a hibát

**Elvárt viselkedés**
Írd le, hogy mit vártál, minek kéne történnie.

**Képernyőképek**
Ha lehetséges kérlek csatolj képeket a problémádról

**Telefon:**
-  Eszköz: \[pl. samsung galaxy j5 2017]
-  OS: \[pl. android 9.0]
-  App Verzió: \[pl. v0.0.2]

**Egyéb infó**
Kiegészítő információ a hibádról

**Comment by Legolaszstudio** [comment]
Köszönjük visszajelzését!
De ammenyiben semmilyen problémát nem tapasztal kérjük ne spammelje a GitHub issue felületet!
